---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortener-secret
  namespace: tsidly-dev
spec:
  encryptedData:
    DB_PASSWORD: AgCoXP58SH0MKUmiiSWUJw1zmahkTWUw2xr1nLUg5093NXUaHJrO5+6fOpp6tJgI8NIQDU/jE//7TULYgQt/B5rlg938XnpS77aWMHxgUalG+K/aRACYO8FJzeGcCAM5AX/1lq1/rFdzGvLrG74uJXzCHUGSbumXwZpSdaI6/nu+z5mnONgSl7YP3rV4Kit3Zy3/TF8c2+DPvWdEynNGf3zVrQOgLvSHrztWjL5XeCeGNgTP1qOq8y12iUAcTN1LnzWi+Cmky0oRPa6tvXZNiZLHxa2RhYkbxYoGAxZkmUJodI0xbOz3Vh+NZ/jqYQlGUuli4D9SE4iXEURI7RF32AEVPdCA/DpCj6tYNIXi2ixPjNODFFzyMP6SmDFS7i0ddaYQ+m/unG/cY1UQ0F/fsN84kSRYS1S1whUTkie+oCbZqjvZ5NWwBkssOlGvlbxNog8gLFgk0i+DfUCqz/E/Inw00vhv1OgTCvqRGICONGD63VLw/yEU4P8sSrW2zYasENTYILHKF4JumA2Lklgb0udmdEbL3TJytXkQLrtS9ew7vu1a38yC5KzNMZMEWz1wwsCVwFzfpREFzkWdSzEsLHnTWE6dGXBUpk/1tsnKJMLA4IR6HDBZ+p8n18/IV/ZPcsz/SolYzC+HeU5EFrZvxdiAURQlkdP4iv+4Vt398IZjtwgSiItMbkrS3Q42MUWjSY5F/NjcT66iwnVn8Q==
    DB_USERNAME: AgCUCvCgViQJKjU6+aW6QBc/FVb7hXvnc9ZttBJVDCr61wwqkh/aE3E+jCEe+8FCFvzJGOG+xwyhEyjrbz2Rxj5qKSgpEHzgrvSWaPJba8u70lZc1AXKk/cn6v0LTFxZWmM3s+BpMpwvNouzgE63rWv5mSHsKRVI1iz2jJ4/SpalAZd3aHeSy/1yQmgvDlTGbDRTNaPlPC49cFp2VsET3ez8RxDsrzgZN1mPppExTnhzPGBGmM23/ga29OB0nPx2rrRWDSoYHLxdRM3aPV+V/DN/GSla4lCfVK1/pfbcK0cikvuef7LkY1ZeL+r4UMTxgF6OQV3k6euCVxZVKgoFKXrw7K2MoNGSW3mitY3Je1nLRu8UqHRrtzLG9PBmcmd2lSzYqUp5szkMxy0BMgwUVddTcU2YDPGD6nWzY1eCgggoXubeGmjiutLlf4JnXu/45C/Zi/xZqec6HAoHmdMPq0cmyMhyPy6LW39636fdxvG/wwL651CRoR57NCn7MoCff1WERkfBXjMK5Accv0DLFP59WoVekjXKE0TwV3iLl7MmADRmcTu61KxEp7cvGO2Z+4uon0buiDzUMHjVfUBvAXXCjWK/ndaQtiP1i4Bie9s433TZRsZstai0q3tc5K1szBFLIggoHZ6JUea58lbTheIzSzsAPGwS2Ch6ji4Uo/sTOE6QrHdMeDEsZXrOY3AlsSPyILX8TMxjzSzFlw==
  template:
    metadata:
      name: shortener-secret
      namespace: tsidly-dev
