{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "shortener-secret",
    "namespace": "tsidly-dev"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "shortener-secret",
        "namespace": "tsidly-dev"
      }
    },
    "encryptedData": {
      "MYSQL_PASSWORD": "AgAjMgDPgB/wo1Nr20N0571SrrFxAasEIXjfvh9R6ardY5IQeKkXGhexE/FsEd/cLKRNl1JerRvShf3l+6mFklHIDNX83uJE/t/6uwN8K4uztVdYREHAhDWoMqW0iLereiKBP8h4sVf/o+VAB1rfYz1K/a16RxtBWZnxJuMvSWE1PLYmMKVbyO9IxEPgj0d1uv9VMcslBlfF6WISMzX2ng7xPwWqSZd2UelB+wmcgNvtNEAwGPH/zL7HJmc069xtikcCcILkQGy1qrlA3Xx7tHXS2wHO3lCFsi6KymMuQ4LkKamaBtT8YOjnA/VkUUdyfbEREMIhJHMyVJ6l5IM9cbRYIyGiuoXumYG9gmaff7EKwNJJRvT+Or8jDEMFakH+UkQn0unKP/yRxh6pzqqgEkJT6WL24jrznMzb/X6MP+wCCCgLjLohFcj9eTaznEXOquOscINlhlWsM+VDO1GJqvEBR80GrJTEE5mDnwLcU68iP/Yetzv9SVbi1lCDVlMJfedzo+0YLcE3YaxI7t0wrArXowq1xyqqLHQbddCsiW1dwm33XmKhseR/+q7mMk0OHbpcbbrEcf2s+DlExlC7pDgkbq3irH2Rply205btXZl/hkhqBZy7MsiZMFWFHwEKtq8c1ZrZCRRFbh1CrROGYyf84c1DkOpTSudj3ZZGmphVWpvUxHf+UEECGVGw/hcEFSdI0snnydCKwyyCXQ==",
      "MYSQL_USER": "AgBtlSIxFWcTbK2OO2VFiJK6hJlc8JhsNgt5ab8wzb4sTncr0TIUnbZkp2AWxXJ2I/nSvJ3lEDU4d6RHe5p3n8+Ec0jjJfen+offxS7l5q2cpaHy1McqIPgrRav2Sd90AR2fznDupqi00cPBnChzvugoMv9fmWlOwKiGt+M0IZ7UeVrhR2GSHt6/CEOKPg4bhLiZX2/uJgj//oQZqOj8WMr8q4/PGvb+2MI10kDsmBRUYMREdnoz+yfyDfjjKaC7uhecwg+8ubWwbxKabVJ2bWZ84Fswad7np35747LBYd05nw+c9LeG2c/XxB1jS0THW6dhStOaEfCDiGlEZpGJ0O86RCG8KZFuG5BuQt3xPyU44Gh4O+Z7RpH4xB+2e3Qpf5RdgZ424qOlxYUN1yq06i40wmTGH6iQFsfib4uJ5HAa16dLb/g4wcXCFPIQXLASWm43yptRj9wq4ekcZIYlWWtJXIVnH1+DRYTzvJt37CgRZAgQCewQ8Z9vZiJII/R2mwIJX4H5VW/tYqB1OQrAY6G6d4paHYv6f5nSGUqQAj05sjRWno12oRXUI02hntG0IA5tsoJxgt2xKEgijYP1c5YLQq3qtAXsRnDXoeVKTuSmG46dOHxTRB9rSCt0jaVdULoP3evXJe2iX6iw+NxHgwmjRmTSr9Mm7KJlrAJuQOCVofySZRX+DSUcEG210vTs7dMauwlc/uWAgaVXBQ=="
    }
  }
}
