apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortener-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgB7OgOd0nXHqJa6M2hno0+Tp+WdtorLP+zLFayHZkKZdvP8j9EO20A9b7c0XZWEvJsDO716nI1+Xz3P2rUsQXCYbEnaT+UGbIfHsSbUbKWDFaBEKa/+elwCjUZO/UkINfn+dmfrnEYd33PpXccUrGP1uk22MMtE5atxnzWACjzk4jAO5jxeBbgESJmMVBeecZDkXULV1G6QWJOrv8K+XN+VdxaHvp2rr3wmCsr1frjrPFjMkI4wMCSPnixjpZqGQ+kxwCEl+60xFOm4w+nkzVDcLDWH2alCzk+Mqf8HOvWhkpkwWZgy0f2uQu+ZwG5mFrHLHFEgKkjrAnsZiwxp8L/ssJJaBGGGSQKaGYnMR5T9itrRN7S6X0CbsF0j3BEurK1NF1yKitCsPw9iEiBJNLgSiDFIOjpNK5llJtMIr39HHPc8wbnoHC4ahAKPO77AS3j+LFJ5XSRoUKr6wlcKcbmjZja/beFiDH6X8Gx6tU39cfZRlRlw6wYYHn7PYhNxJTJr54ydcFVMqQemlfhKhQq1UvXnXN+UoX/OHQdDbM01XGyhFU4gcpcs52Hit9qe4pX6uTvpEvyK+79/+ioA4jWuCPrfzxP2NkFBz6G9x4KvubRXP67FiPhEvW0tdF2YofMHy7wlrBGrb+jlcQSMfWV9lW6mo8Lr+IFEL1vTm0giYfKqnkn10foNRkbe9XF5HdPRnoaSjiE6JzGONQ==
    DB_USERNAME: AgCpYkITSP+6thFQ8TSUcIYZaLjgzNGWyWhIr85eYQ6Z2rPNLk5upOoLTEJ/+YEN9Kgl8Nk07vboWCc+8xNHGPnm4n3C7gVQ/V+psZrfjgeMaaf9ANeLm13gsZyxHbGRb3m6PQe2pTPixvNofqR/L/OItHeLz+TU5WT+GMSTbMvR7wgMdPeT/M6QnUbbHmspDk8szl+jVsmL9Okzr0D376oy6x46HJRQg+iTYOmXU3U4Knk8qIGtKAt7KFjX+lwMyFdWij//DbNyalk5habtLSLdMQNOU2gwGWj2AFwwLQf+JdsTg+QA8jHaz9U3R6ke1So2WenqleQzt/MHRfhNhWt5aLvYBIy8OSl3HaJmrm6lZmqMbqeXL7owSSqwCV//RyL8VFbdc/C92Ug9LQzUcz6PdfrmBFNyBsa5kRR7X08W+wEqgiOfJberlPVRoanPzyppdap7GpusXEGGh0hMsQQ7nBGovhqrXVbFjJ4s4yeAhcJpbvtXG9WX30GyqHxdbunPQ8mIzztEJiv+Qc6NnoX3rV9oaNw16N5nj2KnrXe0+izkyVgIgEla0WpZkisikOrB2zOgyI5U02AtE9BHaTH+0BhITvq8lSFMgRBI9eRwBgv615aBIz0LeD1w4YymKRItCdvkD1YYgvxugS7HpTKqs87xBbcj5z3WDZ/nk/p4eweT5M8mItY+Z4wHfNv55TrjzGIEbCh730GQdQ==
  template:
    metadata:
      name: shortener-secret
      namespace: default
    type: Opaque
