apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect
  labels:
    app: redirect

spec:
  selector:
    matchLabels:
      app: redirect

  template:
    metadata:
      labels:
        app: redirect

    spec:
      containers:
        - name: redirect
          image: kwondeokjae/tsidly-redirect
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8082

          envFrom:
            - configMapRef:
                name: redirect-config
