version: '3.8'

services:
  kafka-1:
    image: apache/kafka:4.2.0
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "${KAFKA_1_EXT_PORT}:${KAFKA_EXT_PORT_INT}"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:${KAFKA_CONTROLLER_PORT},2@kafka-2:${KAFKA_CONTROLLER_PORT},3@kafka-3:${KAFKA_CONTROLLER_PORT}"
      KAFKA_CLUSTER_ID: '${KAFKA_CLUSTER_ID}'

      KAFKA_LISTENERS: "INTERNAL://:${KAFKA_INTERNAL_PORT},EXTERNAL://:${KAFKA_EXT_PORT_INT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-1:${KAFKA_INTERNAL_PORT},EXTERNAL://${KAFKA_ADVERTISED_HOST}:${KAFKA_1_EXT_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_MIN_ISR}
    volumes:
      - kafka1_data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-2:
    image: apache/kafka:4.2.0
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - "${KAFKA_2_EXT_PORT}:${KAFKA_EXT_PORT_INT}"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:${KAFKA_CONTROLLER_PORT},2@kafka-2:${KAFKA_CONTROLLER_PORT},3@kafka-3:${KAFKA_CONTROLLER_PORT}"
      KAFKA_CLUSTER_ID: '${KAFKA_CLUSTER_ID}'

      KAFKA_LISTENERS: "INTERNAL://:${KAFKA_INTERNAL_PORT},EXTERNAL://:${KAFKA_EXT_PORT_INT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-2:${KAFKA_INTERNAL_PORT},EXTERNAL://${KAFKA_ADVERTISED_HOST}:${KAFKA_2_EXT_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_MIN_ISR}
    volumes:
      - kafka2_data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-3:
    image: apache/kafka:4.2.0
    container_name: kafka-3
    hostname: kafka-3
    ports:
      - "${KAFKA_3_EXT_PORT}:${KAFKA_EXT_PORT_INT}"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:${KAFKA_CONTROLLER_PORT},2@kafka-2:${KAFKA_CONTROLLER_PORT},3@kafka-3:${KAFKA_CONTROLLER_PORT}"
      KAFKA_CLUSTER_ID: '${KAFKA_CLUSTER_ID}'

      KAFKA_LISTENERS: "INTERNAL://:${KAFKA_INTERNAL_PORT},EXTERNAL://:${KAFKA_EXT_PORT_INT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-3:${KAFKA_INTERNAL_PORT},EXTERNAL://${KAFKA_ADVERTISED_HOST}:${KAFKA_3_EXT_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_MIN_ISR}
    volumes:
      - kafka3_data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:${KAFKA_UI_PORT_INT}"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-4.2
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-1:${KAFKA_INTERNAL_PORT},kafka-2:${KAFKA_INTERNAL_PORT},kafka-3:${KAFKA_INTERNAL_PORT}"
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka-net

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:

networks:
  kafka-net:
    driver: bridge
