---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortener-secret
  namespace: tsidly-prod
spec:
  encryptedData:
    DB_PASSWORD: AgC4JEbZX2FRMD6ERYDFo1WNysvx8sxjQMVHtJJg5Lg/vMuE+ggYRS3sPxMBXsYTwr1LjwXruOO1HEQQnpt4shMtoelDC391+ZwH41SZkyuFUgxzhS/vSZpvQYUMukowEAivlI9xltphycwn4wek+FnCob02ZU/u5Wl/clLUrNv/92KUHyzvgAzdh7yj3bhI0auIrd+vVuo9T4p5ie//y36XX0gKmmMMyAl2LzDrLFTk0Lw6trPdSe1FSZJmmp43o0twwBpXSW9fd/i5SX/mZUPabHZ/j2h2CwUxyjT6wz48Fiu/pJ+qxXc3+Eb5a7qCPbB9tl9ThGTOm/8LpnDmiIMok8QMRWFRyr4lbpf+PwZ6BPstpbfH1AY87qlSMJaEyGGfQqyfFMZQwKOoz+ZMWKaHdrAkregp/z4qllg2UnIKuSGnyepp+9U0KD8f6fT1OvJlw7whF92iDpdAMLsiDhX6/6BqCxMeX24G+j0fbbLXKMRTUovMkxrLOjxljWK7pUxPMBl3gCvTni3jbE924DZntRJnZc1fKq3h89F5qjkQhSE8GxcW/5bWPUFfKdrksdvVHMCrwkrYfTedoQ8Gh5voWXSB1lUQ11/lmVwASXz+RMyAkXETZox0UUxFdtSypkMl/Tay557DUYHldCeZ69bPLurR26u36H6BZlOCqsRSZh/KYIk4JtQBWAY1fTGIwAgAt1j4ZCrK5kN+4A==
    DB_USERNAME: AgBcp+UONqwqrh/w7+LtRn6g/23WYRoFGTa7waYuSpAeDVVipQYpu+Lyacm/c5jI8SunkwQjLM/zolW7jKRdhvEZWpR77tq9p/wOm1+LcpjMB5XhIAqkI72aP9SMSsA+K6Qu3cz51hd45s0f6AumNPS5To1pY7nxBwKyW0OBxuuGQid/4BXGqFr6d5C29Bx45QwWRf22MyGdXQSzQjDY41QRk1ymGmN1ppUA3gMfzKRNrVZhh9dvGxEwZ9Jy3HUJx5JYn9sMP7TUyV0AUy1dcmKDwSn9FxHzFbOOeM4T2Bfx3FF2XNgyx6NzxhzXV94k38V4Ohgbhsl4uFw5Hz1D3XW/rE7O2q5fJgabDVsAkJ6uHhHzFeB7M8J/u7gcw7P4IyfFlv6q0BI8pjtXDHEwUDTxbSnSEwHZ3AgKmmbB/FTKzG7x0W57n1VCKhBUKEOTja6JqNCQ/bxUQWm9kgqTFOF6z0ms8GU6I5tcS3EF6rFjgjTxoAClzVlI2QvnUUj0CSoOfySXK016Ae8ok2NJKYrnsbgurSjhYjgHVux+xPehWd0p1GuYv6IRG8l7WtWiMk2PQX9/nGbjFrFgTENsR412wry2Ia0ATgU/pnEGaaSuG5vr1qEICtXLwZyDpxg/bZrixxvIn2T/vRQIjzxA88Z1xFnh49k1MRc6ZyJ+QaK9hin5i2wVlOfcZvmc72GxfdKFbgeAVVycSalTfw==
  template:
    metadata:
      name: shortener-secret
      namespace: tsidly-prod
