apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortener-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBB9L1YixopQtGs6+OMs7ocnAIjNdP6LL98jcsSEuXz213pQMKzkRH4tR6JwD7fQSt97DuXP6bDxnOvp5xTucXK934pZxpdK1iA/LV1ADDUsuTu12ZQr02eBf9ShmRLyChACnabmhiipupSfcMD5fOJgYPPK6hNqfRB2QLm+67WaW8J0w8bjy3Bp162fRxBWkpfH2zJN85Y5I++/afgoAY01E+d5c9+auvoblE5h/nsKDy1t4YG7yN/AtuMS1jI1bIIz6TLTGdfUnFPo3JVDMZpdiDKSc0muCTja3D+8DFgoigd0eXMFO3biiUTlNezjk7tqh3wvmFQA1Jc7UkMY8yZp1zksy9WpreuMZrQvY9MU7qn5sYTC4zIDxDFi5pnl2yQkEluxwCSDD/TBXqbaNxKSgy8SXHAnP8m+5/cEnDVUb4AM9jZbbiAlXvCBL3e7/PsVV1fUzPIo8o9rVr8GnncKeLH0rfBdcwf/4hj2J47qp7o7PAd360cPCfvB23HR1vll61VZ5latiQOvLgw7NdXeeXLYf/D1vAGb2A8Enw+6340MIp2x96xRKCJCk3l6wGZLOvD7ohzDAYk+0ZSgzY13XsMwG8M6Gwofm2ZcpCFir6XKMqRXRe/dI0+Lnr17u8dpcD7KCV+jSQNAgRPaN2B5Kqh1L44AcAoy8N9l2Erd44pqMgk1RK8gGu0S5dkuskAcqjZqoMIJzLcPw==
    DB_USERNAME: AgCV1i8tGLKWtNT3UtQvsh+N1AxnQnJ7y4iFP/0EH6IkZcFhS4tgdbnxdlw1ScDJv1AynZWdvKpuRShUdMMFcmN2qwuX7ol+zlUl7ZQ0TykV/zHA47Ud+yxM3ypzn1V35wrp2RA1lFBZOT9EhTSRzoy81HThBa5ApmlWpoMM1r07DKdJVR1sKivFqm14x154NEAB5yLVt2KINt5lcNSyBmwCzdwNWwr8yumLuw6Gfrnh34qSMoaXwbRfQd7KPbPbFRD1Yq1CzF8fsGqiNz++Q5oOai9je3enmpyMg6yF8sK/+XIxH1FYLi2qNBYJNdDwMOR/Z85iWBItSWlJpdfnp4FULflh0t9Hz4bxwqx4MVBALX6d5EXecApmBJJijiStiXiXizYfgOm6p67qCMtq2pph9XCByvCe5eb4bUGAJCXPPwG4Dqd/E9+Xs+EDZQiXmSEDI2aFMjB6u723hcoa0NPe0cqOWbqvMoHCwbKRHzS/+prCDQe3N15fgL0nNjwyKsnVekJeJPLg0W1a+ot7TQ3l5opsRmCZteqHeaCRGMTWu/+YjM/JtCkTcdQ35A5CGUoLqevLVxANO/Acq/1xBUx7w7+e+pzVEJDlhfYownu1wZjUR3/wELu0X1JhdKsLyMa8ih/1xaYrOcLmuykf58S/SOJbmfsX7NmlYSzucC/X59TxkKlITt+ZUR6inTqAYuntFhit2Jnw6+EHWQ==
  template:
    metadata:
      name: shortener-secret
      namespace: default
    type: Opaque
