apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tsidly-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      gateway=kwondeokjae/tsidly-gateway,
      shortener=kwondeokjae/tsidly-shortener,
      redirect=kwondeokjae/tsidly-redirect
    argocd-image-updater.argoproj.io/gateway.update-strategy: newest-build
    argocd-image-updater.argoproj.io/gateway.allow-tags: "regexp:^prod-[0-9]+$"
    argocd-image-updater.argoproj.io/shortener.update-strategy: newest-build
    argocd-image-updater.argoproj.io/shortener.allow-tags: "regexp:^prod-[0-9]+$"
    argocd-image-updater.argoproj.io/redirect.update-strategy: newest-build
    argocd-image-updater.argoproj.io/redirect.allow-tags: "regexp:^prod-[0-9]+$"
    argocd-image-updater.argoproj.io/write-back-method: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/juintination/tsidly.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: tsidly-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
