apiVersion: v1
kind: ConfigMap
metadata:
  name: shortener-config

data:
  DB_HOST: mysql
  DB_PORT: "3306"
  SERVER_TIME_ZONE: UTC
  CHARACTER_ENCODING: utf8
  TSIDLY_DB_NAME: tsidly_db
  REDIRECT_SERVICE_URL: http://redirect-service
  SHORTENER_SERVICE_URL: http://shortener-service
  REDIS_HOST: valkey
  REDIS_PORT: "6379"
