apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
  labels:
    app: shortener

spec:
  selector:
    matchLabels:
      app: shortener

  template:
    metadata:
      labels:
        app: shortener

    spec:
      containers:
        - name: shortener
          image: tsidly/shortener
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          envFrom:
            - configMapRef:
                name: shortener-config
            - secretRef:
                name: shortener-secret
