apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/gateway
  - ../../base/shortener
  - ../../base/redirect
  - ../../infra/mysql
  - ../../infra/valkey
  - ../../infra/ingress
  - ../../secrets/dev/mysql
  - ../../secrets/dev/shortener

images:
  - name: tsidly/gateway
    newTag: latest

  - name: tsidly/shortener
    newTag: latest

  - name: tsidly/redirect
    newTag: latest

patches:
  - path: patch-replicas.yaml
