apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/gateway
  - ../../base/shortener
  - ../../base/redirect
  - ../../infra/mysql
  - ../../infra/valkey
  - ../../infra/ingress
  - ../../secrets/dev/mysql
  - ../../secrets/dev/shortener

images:
  - name: kwondeokjae/tsidly-gateway
  - name: kwondeokjae/tsidly-shortener
  - name: kwondeokjae/tsidly-redirect

patches:
  - path: patch-replicas.yaml
