apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey

spec:
  replicas: 1

  selector:
    matchLabels:
      app: valkey

  template:
    metadata:
      labels:
        app: valkey

    spec:
      containers:
        - name: valkey
          image: valkey/valkey:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 6379

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
